{
  "data": [
    {
      "ActionTrackerID": "12345",
      "PrimaryCategory": "NA",
      "SecondaryCategory": "NA",
      "Priority": "LOW",
      "ActionTitle": "Action Tracker",
      "ActionRemarks": "NA",
      "AddedDate": "29/12/202",
      "PlanFromDate": "28/12/2022",
      "PlanEndDate": "10/01/2023",
      "ActualFinishDate": "15/01/2023",
      "ActionStatus": "PENDING",
      "ActionAuthor": "NA",
      "AssignToUser": "Akshay",
      "NextReminderDate": "16/01/2023"
    },
    {
      "ActionTrackerID": "15452",
      "PrimaryCategory": "NA",
      "SecondaryCategory": "NA",
      "Priority": "LOW",
      "ActionTitle": "Action Tracker1",
      "ActionRemarks": "NA",
      "AddedDate": "29/12/202",
      "PlanFromDate": "28/12/2022",
      "PlanEndDate": "10/01/2023",
      "ActualFinishDate": "15/01/2023",
      "ActionStatus": "COMPLETED",
      "ActionAuthor": "NA",
      "AssignToUser": "chintan",
      "NextReminderDate": "17/01/2023"
    },
    {
      "ActionTrackerID": "15235",
      "PrimaryCategory": "PC-1",
      "SecondaryCategory": "SC-2",
      "Priority": "HIGH",
      "ActionTitle": "Action Tracker2",
      "ActionRemarks": "NA",
      "AddedDate": "29/12/202",
      "PlanFromDate": "28/12/2022",
      "PlanEndDate": "10/01/2023",
      "ActualFinishDate": "15/01/2023",
      "ActionStatus": "COMPLETED",
      "ActionAuthor": "NA",
      "AssignToUser": "Ram",
      "NextReminderDate": "17/01/2023"
    },
    {
      "ActionTrackerID": "15456",
      "PrimaryCategory": "PC-3",
      "SecondaryCategory": "SC-3",
      "Priority": "LOW",
      "ActionTitle": "Action Tracker3",
      "ActionRemarks": "NA",
      "AddedDate": "29/12/202",
      "PlanFromDate": "28/12/2022",
      "PlanEndDate": "10/01/2023",
      "ActualFinishDate": "15/01/2023",
      "ActionStatus": "PENDING",
      "ActionAuthor": "NA",
      "AssignToUser": "Shyam",
      "NextReminderDate": "17/01/2023"
    },
    {
      "ActionTrackerID": "12482",
      "PrimaryCategory": "PC-4",
      "SecondaryCategory": "SC-4",
      "Priority": "LOW",
      "ActionTitle": "Action Tracker1",
      "ActionRemarks": "NA",
      "AddedDate": "29/12/202",
      "PlanFromDate": "28/12/2022",
      "PlanEndDate": "10/01/2023",
      "ActualFinishDate": "15/01/2023",
      "ActionStatus": "COMPLETED",
      "ActionAuthor": "NA",
      "AssignToUser": "Honey",
      "NextReminderDate": "17/01/2023"
    }
  ]
}